# Generated by Django 4.0.4 on 2022-10-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
